name: 'ShellCheck'

on:
  push:
    branches-ignore: ['*-no-ci']
  pull_request:
    branches-ignore: ['*-no-ci']

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

defaults:
  run:
    shell: 'bash'

  # TODO
  # concurrency:
  #   group: '${{ github.ref }}'
  #   cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
