site_name: 'bash-object'
site_url: 'https://hyperupcall.github.io/bash-object'
repo_url: 'https://github.com/hyperupcall/bash-object'
edit_uri: 'edit/main/docs'
site_description: 'Description'
site_author: 'Edwin Kofler'
copyright: '© Edwin Kofler'
remote_branch: 'site'
remote_name: 'origin'
docs_dir: 'docs'
site_dir: 'site'