on:
  workflow_call:
    inputs:
      author:
        type: 'string'
        description: 'Author of the repository'
        default: 'Edwin Kofler'
        required: false

defaults:
  run:
    shell: 'bash'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    if: "github.ref_name == 'main'"
    steps:
      - uses: 'actions/checkout@v4.1.0'
      - run: |
          cat > mkdocs.yml <<EOF
          site_name: '${{ github.event.repository.name }}'
          site_url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'
          repo_url: '${{ github.event.repository.url }}'
          # edit_uri: `edit/${settings.remoteBranchNameSource}/${settings.docsInputDir}/`
          # site_description: "" // TODO
          site_author: '${{ inputs.username }}'
          copyright: '© ${{ inputs.username }}'
          # remote_branch: settings.remoteBranchName
          # remote_name: settings.remoteName
          docs_dir: './docs'
          site_dir: './output'
          EOF
          pipx run mkdocs build -f './mkdocs.yml'
      - uses: 'actions/upload-pages-artifact@v2'
        with:
          path: './output'
  deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - id: 'deployment'
        uses: 'actions/deploy-pages@v2'
